global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_project]
        regex: hw11
        action: keep
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]