# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dialog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dialog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64ialog.proto\x12\x06\x64ialog\";\n\x07Message\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tfriend_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"*\n\x08Messages\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.dialog.Message\",\n\x06\x44ialog\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tfriend_id\x18\x02 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x63\n\rDialogService\x12&\n\x04Send\x12\x0f.dialog.Message\x1a\x0b.dialog.Ack\"\x00\x12*\n\x04List\x12\x0e.dialog.Dialog\x1a\x10.dialog.Messages\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dialog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=83
  _globals['_MESSAGES']._serialized_start=85
  _globals['_MESSAGES']._serialized_end=127
  _globals['_DIALOG']._serialized_start=129
  _globals['_DIALOG']._serialized_end=173
  _globals['_ACK']._serialized_start=175
  _globals['_ACK']._serialized_end=192
  _globals['_DIALOGSERVICE']._serialized_start=194
  _globals['_DIALOGSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
